name: xlstmpt240cu121
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults  # exclude this to work on leonardo
dependencies:
  - cuda=12.1
  - cuda-nvcc=12.1
  - gxx_linux-64=11.2.0
  - python=3.11
  - pip
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - torchvision
  - cmake
  - ninja
  - cuda-toolkit=12.1
  - cuda-cccl=12.1
  - pip:
      - einops
      - pre-commit #==3.6.0
      - ipykernel #==6.29.0
      - dacite #==1.8.1
      - omegaconf #==2.3.0
      - torchmetrics #==1.3.0
      - tqdm #==4.66.1
      - pytest #==8.0.0
      - pytest-xdist #==3.5.0
      - numpy<2.0 #==1.26.4
